version: "3.7"
services:

  wlo-data-analysis:
    build:
      context: ./oeh_data_dashboard
      network: host
    image: oehdatadashboard:latest
    container_name: wlo-data-analysis
    environment:
      - ES_HOST=$ES_HOST
      - MAX_CONN_RETRIES=$MAX_CONN_RETRIES
      - APP_PORT=$APP_PORT
      - ANALYTICS_INITIAL_COUNT=$ANALYTICS_INITIAL_COUNT
      - DEBUG=$DEBUG
    ports:
      - 80:$APP_PORT
    restart: on-failure