version: "3.7"
services:

  wlo-data-analysis:
    build:
      context: .
      network: host
    image: oehdatadashboard:latest
    container_name: wlo-data-analysis
    environment:
      - ES_HOST=$ES_HOST
    restart: on-failure
    network_mode: host