version: "3.7"
services:

  wlo-data-analysis:
    build:
      context: .
    image: oehdatadashboard:latest
    container_name: wlo-data-analysis
    ports:
      - "8050:8050"
    environment:
      - ES_HOST=$ES_HOST
    restart: on-failure